"""Orchestration primitives for nixvibe."""

from .artifacts import generate_artifact_bundle, materialize_artifacts
from .conflicts import resolve_conflict
from .merge import merge_specialist_payloads
from .modes import resolve_mode
from .payloads import PayloadValidationError, validate_payload
from .pipeline import OrchestrationPipelineError, run_pipeline
from .policy_loader import (
    DEFAULT_POLICY_PATH,
    PolicyLoadError,
    PolicyValidationError,
    load_policy,
)
from .router import select_route
from .specialists import build_dispatch_context, run_specialists, with_dispatch_context
from .validation import run_validation
from .workspace import (
    build_repo_context,
    derive_reference_adaptation,
    inspect_reference,
    snapshot_workspace,
)
from .types import (
    ArtifactBundle,
    ArtifactFile,
    ArtifactMaterializationResult,
    ConflictCandidate,
    MergeResult,
    Mode,
    ModeDecision,
    OrchestrationResult,
    OrchestrationPolicy,
    OrchestrationRequest,
    Priority,
    ReferenceAdaptation,
    ReferenceProfile,
    RecommendationPriority,
    RepoContext,
    Route,
    RouteDecision,
    Severity,
    SpecialistExecutionOutcome,
    SpecialistExecutionResult,
    SpecialistDispatchContext,
    SpecialistFinding,
    SpecialistPayload,
    SpecialistRecommendation,
    SpecialistRisk,
    SpecialistStatus,
    SpecialistTask,
    ValidationCommandResult,
    ValidationReport,
    WorkspaceSnapshot,
)

__all__ = [
    "DEFAULT_POLICY_PATH",
    "ArtifactBundle",
    "ArtifactFile",
    "ArtifactMaterializationResult",
    "ConflictCandidate",
    "MergeResult",
    "Mode",
    "ModeDecision",
    "OrchestrationPipelineError",
    "OrchestrationResult",
    "OrchestrationPolicy",
    "OrchestrationRequest",
    "PayloadValidationError",
    "PolicyLoadError",
    "PolicyValidationError",
    "Priority",
    "ReferenceAdaptation",
    "ReferenceProfile",
    "RecommendationPriority",
    "RepoContext",
    "Route",
    "RouteDecision",
    "Severity",
    "SpecialistExecutionOutcome",
    "SpecialistExecutionResult",
    "SpecialistDispatchContext",
    "SpecialistFinding",
    "SpecialistPayload",
    "SpecialistRecommendation",
    "SpecialistRisk",
    "SpecialistStatus",
    "SpecialistTask",
    "ValidationCommandResult",
    "ValidationReport",
    "WorkspaceSnapshot",
    "build_repo_context",
    "build_dispatch_context",
    "derive_reference_adaptation",
    "inspect_reference",
    "load_policy",
    "generate_artifact_bundle",
    "materialize_artifacts",
    "merge_specialist_payloads",
    "resolve_conflict",
    "resolve_mode",
    "run_pipeline",
    "run_specialists",
    "with_dispatch_context",
    "run_validation",
    "snapshot_workspace",
    "select_route",
    "validate_payload",
]
